services:
  streamlit:
    build:
      context: .
    container_name: world-happiness
    ports:
      - 8501:8501
    volumes:
      - ./app:/app
    command: streamlit run main.py --server.port 8501
    restart: always
